Flake8 corr1
SUEPPhysics/SUEPCoffea_dask pull request #150
Opened 2022-12-15 12:57 UTC by chrispap95

I turned on flake8 linting. I fixed a few of the issues that seemed more straightforward. 
Some of the remaining issues are about blocks of code (functions, `for` loops, `if`s) that are massive and too complex. 
I raised the acceptable complexity level but still, some of them are too much. I open this issue so that everyone can push fixes

2023-01-25 14:17 UTC, lucalavezzo requested changes
looks good to me, I have a couple minor comments but nothing really important.
as an aside, I would like to move some of the parts of make_plots into another script to make the main script more readable

2023-01-25 14:43 UTC, chrispap95 commented on plotting/make_plots.py
> +            # if options.era == 2016 or options.era == 2017:
The prefire weights section is already commented out in the code. I am not sure why. But I can reenable it if you want.

2023-01-25 14:53 UTC, chrispap95 commented on workflows/ML_coffea.py
> +        # columns = ["SUEP_nconst_CL", "SUEP_S1_CL"]
done

2023-01-25 14:53 UTC, chrispap95 commented on workflows/CMS_corrections/track_killing_utils.py
> +    # block0_indices = tracks.pt <= 1
done

2023-01-25 14:58 UTC, chrispap95 commented
Btw, I am also pushing some changes to the dask runner so that we kill two birds with one stone (otherwise I would open a new PR very soon).

2023-01-25 15:35 UTC, lucalavezzo commented
Changed the target branch to be working branch, instead of master.
Master should be freezed until paper is done.

2023-01-25 15:49 UTC, chrispap95 commented on plotting/make_plots.py
> +            # if options.era == 2016 or options.era == 2017:
Unfortunately, I have trouble running the systematics at the moment. I can't verify. I will try to find some workaround.

2023-01-25 18:02 UTC, lucalavezzo commented on plotting/make_plots.py
> +            # if options.era == 2016 or options.era == 2017:
I would say to remove the comment; I just tried it and everything ran fine.

2023-01-25 19:27 UTC, chrispap95 commented on plotting/make_plots.py
> +            # if options.era == 2016 or options.era == 2017:
done

2023-01-26 17:56 UTC, lucalavezzo approved these changes

2023-01-26 19:29 UTC, merged